#!/bin/sh

EXEC=/usr/local/redis/bin/redis-server
CLIEXEC=/usr/local/redis/bin/redis-cli
CONFIG_FILE="/usr/local/redis/etc/redis.conf"

PIDFILE=`awk '/^[[:blank:]]*pidfile\s/ { print $2 }' $CONFIG_FILE | tail -n1`
HOST=`awk '/^[[:blank:]]*bind/ { print $2 }' $CONFIG_FILE | tail -n1`
PORT=`awk '/^[[:blank:]]*port/ { print $2 }' $CONFIG_FILE | tail -n1`
PASS=`awk '/^[[:blank:]]*requirepass/ { print $2 }' $CONFIG_FILE | tail -n1`
SOCK=`awk '/^[[:blank:]]*unixsocket\s/ { print $2 }' $CONFIG_FILE | tail -n1`

###############
# SysV Init Information
# chkconfig: - 58 74
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis server..."
            $EXEC $CONFIG_FILE
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            [ -z "$PASS"  ] || ADDITIONAL_PARAMS="-a $PASS"
            if [ -e "$SOCK" ] ; then
               $CLIEXEC -s $SOCK $ADDITIONAL_PARAMS shutdown
            else
               $CLIEXEC -h $HOST -p $PORT $ADDITIONAL_PARAMS shutdown 2>/dev/null
            fi
        fi
        ;;
    status)
        # PID=$(cat $PIDFILE)
        # if [ ! -x /proc/${PID} ]
        if [ ! -f $PIDFILE ]
        then
           echo -e "\033[32m Redis is not running  \033[0m"
        else
           echo -e "\033[32m Redis is running. pid is `cat $PIDFILE` \033[0m"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac